name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Storybook
        run: npm run build-storybook
        
      - name: Run Ensure Headers Script
        run: |
          # Run the script to ensure all HTML files have proper headers and service worker
          node .storybook/ensure-headers.js
          
      - name: Verify Service Worker Files
        run: |
          # Verify that the service worker files are in the storybook-static directory
          echo "Checking for service worker files:"
          if [ -f "storybook-static/gh-pages-coi.js" ]; then echo "✓ gh-pages-coi.js"; else echo "✗ gh-pages-coi.js is missing!"; exit 1; fi
          if [ -f "storybook-static/gh-pages-coi-sw.js" ]; then echo "✓ gh-pages-coi-sw.js"; else echo "✗ gh-pages-coi-sw.js is missing!"; exit 1; fi
      
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: storybook-static
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 