name: Test Suite

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Run unit tests
        # Continue even if tests fail
        continue-on-error: true
        run: npm test
        
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: |
            vitest-result.json
            coverage/
          retention-days: 30
        
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      # Skip Playwright browser installation when running locally with act
      - name: Check if running in GitHub Actions
        id: check_github
        run: echo "::set-output name=is_github::true"
        if: ${{ !env.ACT }}
        
      - name: Install Playwright browsers
        if: steps.check_github.outputs.is_github == 'true'
        run: npx playwright install --with-deps
        
      - name: Start Storybook in background
        if: steps.check_github.outputs.is_github == 'true'
        run: npm run storybook &
        
      - name: Wait for Storybook to be ready
        if: steps.check_github.outputs.is_github == 'true'
        run: |
          npm install -g wait-on
          wait-on http://localhost:6006
        
      - name: Run component tests
        if: steps.check_github.outputs.is_github == 'true'
        # Continue even if tests fail
        continue-on-error: true
        run: npm run test:component
        
      - name: Upload Playwright report
        if: always() && steps.check_github.outputs.is_github == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30 